server:
  port: 8080
  servlet:
    session:
      timeout: 15m
spring:
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 100
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
  sql:
    init:
      mode: embedded
  security:
    user:
      name: test
      password: test
